# Generated by Django 4.0.6 on 2022-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.CharField(choices=[('work', 'work'), ('study', 'study'), ('others', 'others')], default='study', max_length=6),
        ),
    ]
