# Generated by Django 4.0.6 on 2022-08-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='categories',
            new_name='category',
        ),
    ]
