# Generated by Django 4.0.6 on 2022-08-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
